[".local/share/zsh-snap"]
type  = "git-repo"
url   = "https://github.com/marlonrichert/zsh-snap.git"
exact = true
refreshPeriod = "168h" # once a week

[".local/share/zsh/site-functions/_pip"]
type  = "file"
url   = "https://gist.github.com/blueyed/54a257c411310a28805a/raw/_pip.zsh"
refreshPeriod = "168h" # once a week

[".config/k9s/plugins/flux.yaml"]
type = "file"
url  = "https://raw.githubusercontent.com/derailed/k9s/refs/heads/master/plugins/flux.yaml"
refreshPeriod = "168h" # once a week

[".config/k9s/plugins/external-secrets.yaml"]
type = "file"
url  = "https://raw.githubusercontent.com/derailed/k9s/refs/heads/master/plugins/external-secrets.yaml"
refreshPeriod = "168h" # once a week

[".config/k9s/plugins/cert-manager.yaml"]
type = "file"
url  = "https://raw.githubusercontent.com/derailed/k9s/refs/heads/master/plugins/cert-manager.yaml"
refreshPeriod = "168h" # once a week

[".config/k9s/plugins/cnpg.yaml"]
type = "file"
url  = "https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/refs/heads/main/docs/src/samples/k9s/plugins.yml"
refreshPeriod = "168h" # once a week
